// AUTO-GENERATED from docs/dronops_requirements_seed.sql (seed v1.0 + Oman v1.1 + ISO v1.2 (2026-06-07)).
// Do not hand-edit — re-run scripts/convert-seed.mjs. Summaries are verbatim,
// QM-reviewed content; kind/jurisdiction are derived per the seed conversion rules.
import type { RequirementDef } from "./types";

export const ac10701: RequirementDef[] = [
  {"id":"AC107-01:PILOT-LOG","framework":"GACA AC 107-01","clause":"Flight time recording","title":"Pilot logbook minimum contents","summary":"Pilots and related personnel should maintain a logbook (paper or electronic, producible to GACA) recording name, UA type and serial, flight time, purpose and outcome of flight, and operational/training details — supporting certificate renewal and scope changes.","recordTypes":["flight_record","personnel_record"],"version":"AC 107-01","kind":"guidance","jurisdiction":"KSA"},
  {"id":"AC107-01:MAINT-LOG","framework":"GACA AC 107-01","clause":"§ 107.123(b) maintenance","title":"Aircraft maintenance logbook contents","summary":"Maintenance logbooks should record UA model/serial, engine and propeller identification, GCS details, defects and rectifications with component changes, time in service of aircraft and components, finite-life/overhaul item times, airworthiness directive and service-information tracking, purpose of flight and area, pilot identification, and legible records of all inspections (date, inspector) and modifications.","recordTypes":["maintenance_record"],"version":"AC 107-01","kind":"guidance","jurisdiction":"KSA"},
  {"id":"AC107-01:CREW-AUTH","framework":"GACA AC 107-01","clause":"Observers and support crew","title":"Written crew authorization and ongoing training records","summary":"Observers and support crew should be trained and authorized in writing by the operator, with records of ongoing training and site authorizations held by operator and crew member.","recordTypes":["training_record","personnel_record"],"version":"AC 107-01","kind":"guidance","jurisdiction":"KSA"},
  {"id":"AC107-01:DOC-AMEND","framework":"GACA AC 107-01","clause":"§ 107.123(b)(15)","title":"Controlled amendment of certificated documentation","summary":"Operators need an amendment process for application documentation: list of effective pages, chronological amendment record, and an amendment control sheet tracking the process.","recordTypes":["document"],"version":"AC 107-01","kind":"guidance","jurisdiction":"KSA"},
  {"id":"AC107-01:INFOSEC","framework":"GACA AC 107-01","clause":"Security measures","title":"Protection of information and record-keeping systems","summary":"Operators should implement measures against unauthorized access to information and record-keeping systems.","recordTypes":["document","audit_pack"],"version":"AC 107-01","kind":"guidance","jurisdiction":"KSA"},
];
