// AUTO-GENERATED from docs/dronops_requirements_seed.sql (seed v1.0 + Oman v1.1 (2026-06-07)).
// Do not hand-edit — re-run scripts/convert-seed.mjs. Summaries are verbatim,
// QM-reviewed content; kind/jurisdiction are derived per the seed conversion rules.
import type { RequirementDef } from "./types";

export const car102: RequirementDef[] = [
  {"id":"CAR102:015","framework":"CAR-102","clause":"CAR 102.015","title":"No falsification, reproduction or alteration","summary":"Fraudulent or intentionally false statements, and reproduction or alteration of certificates, records or reports required under CAR-102, are prohibited and ground certificate action.","recordTypes":["document","flight_record"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:020","framework":"CAR-102","clause":"CAR 102.020","title":"Operation only in approved areas (green zones)","summary":"RPA may be operated only in areas approved by the Authority; per the May 2026 resumption circular, operations are permitted within designated green zones identified on the Serb platform.","recordTypes":["mission_record"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:025-12","framework":"CAR-102","clause":"CAR 102.025(12)","title":"36-month retention of liability-relevant records","summary":"Operators must retain for at least 36 months any records that could serve to establish responsibilities and liability between operators, remote pilots and other parties; stored protected from damage, alteration and theft.","recordTypes":["flight_record","maintenance_record","audit_pack"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:065","framework":"CAR-102","clause":"CAR 102.065 / 102.305\\u2013315","title":"RPA Operator Certificate (ROC) for certain operations","summary":"Certain RPA operations require certification as an RPA Operator; application, eligibility and conditions per Subpart F, including documented practices and procedures.","recordTypes":["document","declaration"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:075","framework":"CAR-102","clause":"CAR 102.075","title":"No operation over populous areas","summary":"RPA must not be operated over populous areas except as approved; mission planning must demonstrate compliance.","recordTypes":["mission_record","risk_assessment"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:115","framework":"CAR-102","clause":"CAR 102.115","title":"Operational records control and 24-month retention","summary":"The operator must establish and implement procedures to control UA operation records; records stored protected from damage, alteration and theft and retained at least 24 months.","recordTypes":["flight_record","document","audit_pack"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:125","framework":"CAR-102","clause":"CAR 102.125","title":"Autonomous operations conditions","summary":"Autonomous RPA operations are subject to the conditions of this clause and associated approvals.","recordTypes":["mission_record"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:150","framework":"CAR-102","clause":"CAR 102.150 / 102.240","title":"Controlled airspace and sense-and-avoid approval","summary":"Operations in controlled airspace require special approval including sense-and-avoid capability requirements; prohibited/restricted area rules apply.","recordTypes":["mission_record"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:180","framework":"CAR-102","clause":"CAR 102.180","title":"Maintenance, inspections and condition for safe operation","summary":"RPA must be maintained and inspected and be in a condition for safe operation before flight.","recordTypes":["maintenance_record","mission_record"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:185","framework":"CAR-102","clause":"CAR 102.185 / 102.190","title":"Remote pilot medical condition and incapacitation","summary":"Remote pilots must meet medical condition requirements; physical or mental incapacitation prohibits operation.","recordTypes":["credential"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:195","framework":"CAR-102","clause":"Subpart D/E (102.195\\u2013270)","title":"Remote pilot certification and licensing","summary":"Remote pilots require certification (Subpart D) and, where applicable, a Remote Pilot Licence (Subpart E) with eligibility, conditions, duration and cancellation provisions.","recordTypes":["credential","training_record"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:320","framework":"CAR-102","clause":"CAR 102.320","title":"Chief Remote Pilot functions and duties","summary":"Certified RPA operators must designate a Chief Remote Pilot with defined functions and duties over operational standards and crew.","recordTypes":["personnel_record","document"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:335","framework":"CAR-102","clause":"CAR 102.335","title":"Personnel compliance with operator procedures","summary":"Persons must comply with the certified RPA operator\\u2019s documented practices and procedures.","recordTypes":["document","training_record"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:G-IMM","framework":"CAR-102","clause":"Subpart G","title":"Immediate reporting of accidents and serious incidents","summary":"Accidents or serious incidents involving moderate/fatal injury, drone crash, or jeopardy to other aircraft or the public must be reported immediately to the 24-hour CAA Flight Safety Department (telephone/email channels published in Subpart G).","recordTypes":["occurrence"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
  {"id":"CAR102:G-3D","framework":"CAR-102","clause":"Subpart G","title":"Listed incident types reported within 3 days","summary":"Listed incident types involving drone operations must be reported via the CAA incident reporting system (caa.gov.om) within three days of occurrence.","recordTypes":["occurrence"],"version":"v0.20","kind":"regulation","jurisdiction":"Oman"},
];
