// AUTO-GENERATED from docs/dronops_requirements_seed.sql (seed v1.0 (2026-06-07)).
// Do not hand-edit — re-run scripts/convert-seed.mjs. Summaries are verbatim,
// QM-reviewed content; kind/jurisdiction are derived per the seed conversion rules.
import type { RequirementDef } from "./types";

export const caruac: RequirementDef[] = [
  {"id":"CARUAC:015a","framework":"CAR-UAC","clause":"UAC.015(a)","title":"Accountable person appointed","summary":"Operator must appoint an accountable person with corporate authority and funding access responsible for regulatory compliance.","recordTypes":["document","personnel_record"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:015b","framework":"CAR-UAC","clause":"UAC.015(b)","title":"Registration and insurance before operation","summary":"Every UA must be registered and appropriately insured before any operation commences.","recordTypes":["registration","insurance"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:015c","framework":"CAR-UAC","clause":"UAC.015(c)","title":"Change notification to authority","summary":"Operator must notify GCAA/LAA in sufficient time before changes to accountable person, operator details, UA types, fleet size, or type of operations.","recordTypes":["document"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:015d","framework":"CAR-UAC","clause":"UAC.015(d)","title":"Equipment serviceability and maintenance","summary":"All UA instruments and equipment required for safe operation must be available, serviceable, and maintained per manufacturer and operator maintenance instructions.","recordTypes":["maintenance_record"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:015e","framework":"CAR-UAC","clause":"UAC.015(e)","title":"Pilot competence assurance","summary":"Operator must ensure each UA pilot is competent for the intended operation with required skills and regulatory knowledge.","recordTypes":["credential","training_record"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:015f","framework":"CAR-UAC","clause":"UAC.015(f)","title":"Controlled storage and release of UA","summary":"UA must be stored securely and released for pilot use in a controlled, documented manner.","recordTypes":["document","mission_record"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:015h","framework":"CAR-UAC","clause":"UAC.015(h)","title":"Operational records control and 24-month retention","summary":"Operator must establish procedures to control UA operation records; records protected from damage, alteration and theft, retained at least 24 months.","recordTypes":["flight_record","document","audit_pack"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:015h-AMC","framework":"CAR-UAC","clause":"AMC to UAC.015(h)","title":"Flight mission log minimum contents","summary":"Flight logs must include date, route/GPS coordinates, start/end times, pilot name, observations/incidents/equipment failures, airspace approval reference, UA details (model, serial, registration, weight, colour), and pilot training certificate/licence references.","recordTypes":["flight_record"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:020","framework":"CAR-UAC","clause":"UAC.020","title":"UA pilot licensing","summary":"Pilots must hold the applicable GCAA UA pilot licence for the operation conducted.","recordTypes":["credential"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:025","framework":"CAR-UAC","clause":"UAC.025","title":"Airspace approval per operation","summary":"UA operations require applicable airspace approval; approvals must be obtained and referenced before flight.","recordTypes":["mission_record"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:035a","framework":"CAR-UAC","clause":"UAC.035(a-c)","title":"Accident and serious incident reporting within 3 hours","summary":"Accidents and serious incidents must be reported to GCAA (and local police for accidents) within 3 hours with all pertinent information; follow-up report on preventive actions where relevant.","recordTypes":["occurrence","finding"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:035d","framework":"CAR-UAC","clause":"UAC.035(d)","title":"Occurrence reporting via ROSI","summary":"Operator must report occurrences (crashes, signal interference, near miss, collisions, public nuisance, operations outside assigned area, injuries, lost UA) to GCAA through the ROSI system.","recordTypes":["occurrence"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:040","framework":"CAR-UAC","clause":"UAC.040","title":"UOA continued validity (annual)","summary":"UA Operator Authorisation is valid for one year subject to continued compliance, valid security clearance, and authority access to facilities, equipment, documents and records at any time.","recordTypes":["document","audit_pack"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
  {"id":"CARUAC:045","framework":"CAR-UAC","clause":"UAC.045","title":"Oversight findings and CAPA timelines","summary":"Authority surveillance findings are classified Level 1/2/3 requiring corrective action plans within 7/60/90 calendar days respectively; repeated Level 2 findings escalate to Level 1.","recordTypes":["finding"],"version":"Issue 02","kind":"regulation","jurisdiction":"UAE-Federal"},
];
