// AUTO-GENERATED from docs/dronops_requirements_seed.sql (seed v1.0 + Oman v1.1 (2026-06-07)).
// Do not hand-edit — re-run scripts/convert-seed.mjs. Summaries are verbatim,
// QM-reviewed content; kind/jurisdiction are derived per the seed conversion rules.
import type { RequirementDef } from "./types";

export const dcar: RequirementDef[] = [
  {"id":"DCAR:ORG-AUTH","framework":"DCAR-UAS","clause":"UAS.ORG","title":"Operator authorization and DCAR compliance declaration","summary":"Operator organizations must be authorized and registered with DCAA, declare compliance with DCAR-UAS, and hold a Dubai UAS Operator Authorization; advanced category requires DUOSAM safety approval.","recordTypes":["document","declaration"],"version":"Issue 03","kind":"regulation","jurisdiction":"UAE-Dubai"},
  {"id":"DCAR:ORG-REG","framework":"DCAR-UAS","clause":"UAS.ORG","title":"Registration of all personnel and assets","summary":"Operator must register all personnel and assets involved in operations (pilots, operation crew, maintenance crew, safety personnel, UA, ground controllers, payloads, safety add-ons) and keep registrations updated on change.","recordTypes":["personnel_record","registration"],"version":"Issue 03","kind":"regulation","jurisdiction":"UAE-Dubai"},
  {"id":"DCAR:UOR-RECORDS","framework":"DCAR-UAS","clause":"UAS.UOR","title":"Operational records control and 24-month retention","summary":"Operator must establish and implement procedures controlling UA operation records; records stored protected from damage, alteration and theft, retained at least 24 months, and provided to DCAA on request.","recordTypes":["flight_record","document","audit_pack"],"version":"Issue 03","kind":"regulation","jurisdiction":"UAE-Dubai"},
  {"id":"DCAR:UOR-AMEND","framework":"DCAR-UAS","clause":"UAS.UOR","title":"Notification of process and manual amendments","summary":"Operator must notify DCAA of amendments to processes, procedures and manuals including pre-flight, flight, post-flight, training, safety and emergency management.","recordTypes":["document"],"version":"Issue 03","kind":"regulation","jurisdiction":"UAE-Dubai"},
  {"id":"DCAR:UOR-CREW","framework":"DCAR-UAS","clause":"UAS.UOR","title":"Crew qualification and competence","summary":"Operator must ensure operational crews are qualified and competent for the intended operations.","recordTypes":["credential","training_record"],"version":"Issue 03","kind":"regulation","jurisdiction":"UAE-Dubai"},
  {"id":"DCAR:UOR-FLTLOG","framework":"DCAR-UAS","clause":"UAS.UOR","title":"Flight log maintained and pilot-signed","summary":"During operations flight logs must be properly maintained, all observations and incidents recorded, and the flight log signed by the UA pilot at the end of the operation.","recordTypes":["flight_record"],"version":"Issue 03","kind":"regulation","jurisdiction":"UAE-Dubai"},
  {"id":"DCAR:OM-RETENTION","framework":"DCAR-UAS","clause":"DUOSAM OM — Retention","title":"Three-year retention for advanced-category documentation","summary":"All important operation documents kept (digital or analogue) at least 3 years after end of operation; personnel records 3 years after the person leaves or changes position; protected against loss/alteration; available for authority inspection. Covers authorizations, flight records, maintenance records, qualification/training records, and safety meeting minutes.","recordTypes":["flight_record","maintenance_record","training_record","management_review","audit_pack"],"version":"Issue 03","kind":"regulation","jurisdiction":"UAE-Dubai"},
  {"id":"DCAR:OM-DOCCTRL","framework":"DCAR-UAS","clause":"DUOSAM OM — Document control","title":"Controlled distribution and current-version discipline","summary":"Employees must receive current document sets and revision updates; current revision lists maintained and accessible; authorized-personnel lists kept for maintenance, pre/post-flight inspections, and qualified remote pilots.","recordTypes":["document","personnel_record"],"version":"Issue 03","kind":"regulation","jurisdiction":"UAE-Dubai"},
  {"id":"DCAR:OM-DUTY","framework":"DCAR-UAS","clause":"DUOSAM OM — Duty (OSO#17)","title":"Duty hours and rest period limits","summary":"Flight duty hour maxima and rest period minima apply to all crew involved in UAS operations; company agreements may tighten but never extend the limits.","recordTypes":["duty_record"],"version":"Issue 03","kind":"regulation","jurisdiction":"UAE-Dubai"},
  {"id":"DCAR:OM-OCC72","framework":"DCAR-UAS","clause":"DUOSAM OM — Occurrence reporting","title":"72-hour occurrence reporting to DCAA","summary":"Occurrences endangering aircraft, persons, equipment or installations, and related safety information, must be reported to DCAA within 72 hours of awareness; accidents, serious incidents and property damage additionally reported.","recordTypes":["occurrence"],"version":"Issue 03","kind":"regulation","jurisdiction":"UAE-Dubai"},
  {"id":"DCAR:OM-ERP","framework":"DCAR-UAS","clause":"DUOSAM OM — Part E","title":"Emergency response plan and training records","summary":"An ERP must exist with preparation/briefing procedures and post-emergency reporting obligations; ERP training conducted and recorded per crew member.","recordTypes":["document","training_record"],"version":"Issue 03","kind":"regulation","jurisdiction":"UAE-Dubai"},
  {"id":"DCAR:OM-MAINT","framework":"DCAR-UAS","clause":"DUOSAM OM — Part M","title":"Maintenance program, software updates and evidence","summary":"Maintenance procedures including software/firmware update control must be documented, with evidence records (e.g. technical logbook, flight tests of contingency and emergency procedures).","recordTypes":["maintenance_record"],"version":"Issue 03","kind":"regulation","jurisdiction":"UAE-Dubai"},
];
