// AUTO-GENERATED from docs/dronops_requirements_seed.sql (seed v1.0 + Oman v1.1 (2026-06-07)).
// Do not hand-edit — re-run scripts/convert-seed.mjs. Summaries are verbatim,
// QM-reviewed content; kind/jurisdiction are derived per the seed conversion rules.
import type { RequirementDef } from "./types";

export const gacar107: RequirementDef[] = [
  {"id":"GACAR107:107.5","framework":"GACAR Part 107","clause":"§ 107.5","title":"No falsification of records","summary":"No fraudulent or intentionally false statements in any application, record, report or document required under this Part; falsification grounds for certificate action.","recordTypes":["document","flight_record"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.7","framework":"GACAR Part 107","clause":"§ 107.7","title":"Inspection and demonstration of compliance","summary":"Certificate holders must, on GACA request, make available certificates, documents and records and allow inspection/testing to determine compliance.","recordTypes":["audit_pack"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.9","framework":"GACAR Part 107","clause":"§ 107.9","title":"Occurrence reporting within 10 days; NTSC for serious","summary":"RPIC must report to GACA within 10 calendar days operations involving serious injury or loss of consciousness, property damage (other than the UA), missing/inaccessible UA, fly-away, or manned-aircraft interference; serious incidents/accidents also to NTSC.","recordTypes":["occurrence"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.19","framework":"GACAR Part 107","clause":"§ 107.19","title":"Condition for safe operation","summary":"No operation unless the UAS is in a condition for safe operation; pre-flight checks must confirm this and operation must cease when no longer safe.","recordTypes":["mission_record","maintenance_record"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.57","framework":"GACAR Part 107","clause":"§ 107.57","title":"Preflight assessment, briefing, checks and 3-year flight logbook","summary":"Before flight the RPIC must assess the operating environment (weather, airspace and restrictions, persons/property, ground hazards), brief all participants on conditions, emergency/contingency procedures, roles and hazards, verify control links and power. All flights recorded in a logbook with date, time, PIC and crew, aircraft registration, take-off/landing areas, total flight time, type of operation, flight rules, and deviations; records kept 3 years and ready for inspection.","recordTypes":["flight_record","mission_record"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.59","framework":"GACAR Part 107","clause":"§ 107.59","title":"Operating limitations for small UA","summary":"Operations must remain within the prescribed limitations (altitude, speed, visibility and related constraints) applicable to the category and authorization.","recordTypes":["flight_record","mission_record"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.71","framework":"GACAR Part 107","clause":"§ 107.71","title":"Aeronautical knowledge recency (24 months)","summary":"No person may operate a small UAS unless they passed an initial or recurrent knowledge test or recognized training within the previous 24 calendar months.","recordTypes":["credential","training_record"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.117","framework":"GACAR Part 107","clause":"§ 107.117","title":"Operations Manager duties and reference library","summary":"The Operations Manager must ensure operations comply with the Part, maintain qualification records of every person operating UAS, monitor operational standards and proficiency, and maintain a complete current reference library: operations manual, operational flight plans, remote pilot certificates, operational authorizations, operations risk assessments, declarations of compliance, UOC, and SMS documents.","recordTypes":["document","credential","risk_assessment","declaration"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.123","framework":"GACAR Part 107","clause":"§ 107.123","title":"OA/UOC application content (manuals, RA, procedures)","summary":"Applications must address responsible persons, locations, an operational risk assessment with mitigations, occurrence reporting procedures, personnel licensing/training/medical requirements, aircraft and control station details, maintenance procedures, in-flight procedures including minimum distances, and cargo/dangerous-goods procedures where intended.","recordTypes":["document","risk_assessment"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.133","framework":"GACAR Part 107","clause":"§ 107.133","title":"Operate within OA/UOC conditions","summary":"Operations must comply with the conditions and limitations stated in the Operational Authorization or UAS Operator Certificate.","recordTypes":["mission_record"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.135","framework":"GACAR Part 107","clause":"§ 107.135","title":"Notification of changes to application basis","summary":"Changes to the matters addressed in the OA/UOC application must be managed and notified per GACA requirements before implementation.","recordTypes":["document"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.139","framework":"GACAR Part 107","clause":"§ 107.139","title":"UOC records: crew per flight and maintenance, 3-year retention","summary":"UOC holders must maintain records naming remote pilots and crew for each flight with flight times, and records of maintenance, modification or repair (who performed, dates, parts/equipment for modifications, completion instructions); records transferred with ownership, available to GACA on request, retained 3 years after creation.","recordTypes":["flight_record","maintenance_record","personnel_record"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.145","framework":"GACAR Part 107","clause":"§ 107.145","title":"Personnel compliance with documented procedures","summary":"Persons employed by or assisting an operator must comply with the operator's documented practices and procedures.","recordTypes":["document","training_record"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.149","framework":"GACAR Part 107","clause":"§ 107.149","title":"Safety Management System","summary":"UOC operators must have an SMS including safety policy, hazard identification and risk management for aviation and third-party risks, internal reporting and analysis of hazards/incidents/accidents with recurrence prevention, measurable safety goals, internal audits and regular management reviews, and competency training — documented and scaled to the organization.","recordTypes":["occurrence","finding","management_review","risk_assessment","training_record"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.171","framework":"GACAR Part 107","clause":"§ 107.171","title":"Insurance for Specific operations","summary":"Adequate third-party and cargo liability insurance must exist for every flight regardless of ownership/lease, covering damage, injury, war, terrorism, hijacking, sabotage, unlawful seizure and civil commotion; dangerous-goods carriage explicitly listed where applicable.","recordTypes":["insurance"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.203","framework":"GACAR Part 107","clause":"§ 107.203 (Subpart E)","title":"Declaration of Compliance where required","summary":"UAS used for operations requiring a declared performance standard must be covered by a Declaration of Compliance to GACA (manufacturer or operator declaration).","recordTypes":["declaration"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.211","framework":"GACAR Part 107","clause":"§ 107.211","title":"Declared-UAS documentation to owners","summary":"Declarants must make available to owners a maintenance program (servicing instructions and inspection program), mandatory actions, and a UAS operating manual covering system description, weight/CG limits, altitude/velocity envelopes, environmental effects, crew-injury characteristics, third-party protection features, and degradation warnings.","recordTypes":["document","maintenance_record"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
  {"id":"GACAR107:107.213","framework":"GACAR Part 107","clause":"§ 107.213","title":"Declaration record retention","summary":"Records supporting a Declaration of Compliance must be retained per Subpart E and made available to GACA.","recordTypes":["declaration","audit_pack"],"version":"v5.0","kind":"regulation","jurisdiction":"KSA"},
];
