// AUTO-GENERATED from docs/dronops_requirements_seed.sql (seed v1.0 + Oman v1.1 + ISO v1.2 + category re-tag v1.3 (2026-06-07)).
// Do not hand-edit — re-run scripts/convert-seed.mjs. Summaries are verbatim,
// QM-reviewed content; kind/jurisdiction are derived per the seed conversion rules.
import type { RequirementDef } from "./types";

export const iso9001: RequirementDef[] = [
  {"id":"ISO9001:4.1","framework":"ISO 9001","clause":"4.1","title":"Understanding the organization and its context","summary":"Determine the external and internal issues relevant to the QMS purpose and strategic direction, and monitor and review information about them.","recordTypes":["document","risk_assessment"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:4.2","framework":"ISO 9001","clause":"4.2","title":"Needs and expectations of interested parties","summary":"Determine the interested parties relevant to the QMS and their relevant requirements, and monitor and review this information.","recordTypes":["document"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:4.4","framework":"ISO 9001","clause":"4.4","title":"Quality management system and its processes","summary":"Establish, implement, maintain and continually improve the QMS including the processes needed, their sequence and interaction, criteria and methods, resources, responsibilities, risks, and process performance.","recordTypes":["document"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:5.1","framework":"ISO 9001","clause":"5.1","title":"Leadership and commitment","summary":"Top management must demonstrate leadership and commitment to the QMS and to customer focus, including accountability for effectiveness and integration of QMS requirements into business processes.","recordTypes":["document","management_review"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:5.2","framework":"ISO 9001","clause":"5.2","title":"Quality policy","summary":"Establish, communicate and make available a quality policy appropriate to the organization, providing a framework for objectives and a commitment to satisfy requirements and continual improvement.","recordTypes":["document"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:5.3","framework":"ISO 9001","clause":"5.3","title":"Organizational roles, responsibilities and authorities","summary":"Assign, communicate and maintain responsibilities and authorities for relevant roles, including ensuring QMS conformity, process outputs, reporting on performance, and customer focus.","recordTypes":["document","personnel_record"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:6.1","framework":"ISO 9001","clause":"6.1","title":"Actions to address risks and opportunities","summary":"Plan actions to address the risks and opportunities determined from context and interested parties, integrate them into QMS processes, and evaluate their effectiveness.","recordTypes":["risk_assessment","finding"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:6.2","framework":"ISO 9001","clause":"6.2","title":"Quality objectives and planning to achieve them","summary":"Establish measurable quality objectives at relevant functions and levels, consistent with the policy, and plan how they will be achieved, monitored and updated.","recordTypes":["document","management_review"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:7.1.5","framework":"ISO 9001","clause":"7.1.5","title":"Monitoring and measuring resources","summary":"Provide and maintain suitable monitoring and measuring resources; where measurement traceability is required, calibrate or verify equipment against traceable standards and retain records.","recordTypes":["maintenance_record","document"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:7.2","framework":"ISO 9001","clause":"7.2","title":"Competence","summary":"Determine necessary competence for persons affecting QMS performance, ensure competence on the basis of education, training or experience, take actions to acquire it, and retain evidence.","recordTypes":["training_record","credential","personnel_record"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:7.5","framework":"ISO 9001","clause":"7.5","title":"Documented information","summary":"Create, identify, format, review and approve documented information for adequacy, and control its distribution, access, storage, version, retention and disposition; control documents of external origin.","recordTypes":["document","audit_pack"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:8.4","framework":"ISO 9001","clause":"8.4","title":"Control of externally provided processes, products and services","summary":"Ensure externally provided processes, products and services conform to requirements: evaluate, select, monitor and re-evaluate external providers based on their ability to meet requirements, and retain records.","recordTypes":["document","finding"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:8.5","framework":"ISO 9001","clause":"8.5","title":"Production and service provision","summary":"Control the provision of services under controlled conditions: available documented information, suitable resources, monitoring activities, competent persons, identification and traceability, and control of changes.","recordTypes":["mission_record","flight_record","document"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:8.6","framework":"ISO 9001","clause":"8.6","title":"Release of products and services","summary":"Verify that requirements have been met before releasing products and services to the customer, with evidence of conformity and traceability to the authorizing person.","recordTypes":["mission_record","flight_record"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:8.7","framework":"ISO 9001","clause":"8.7","title":"Control of nonconforming outputs","summary":"Identify and control outputs that do not conform to requirements to prevent unintended use or delivery; take appropriate action (correction, segregation, return, concession) and retain records of the nonconformity and actions.","recordTypes":["finding"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:9.1","framework":"ISO 9001","clause":"9.1","title":"Monitoring, measurement, analysis and evaluation","summary":"Determine what needs monitoring and measuring, the methods, and when; evaluate QMS performance and effectiveness and customer satisfaction; analyse and evaluate the resulting data and retain evidence.","recordTypes":["management_review","audit_pack"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:9.2","framework":"ISO 9001","clause":"9.2","title":"Internal audit","summary":"Conduct internal audits at planned intervals to confirm the QMS conforms to requirements and is effectively implemented; plan a programme, define criteria and scope, ensure auditor objectivity, report results, and act on findings.","recordTypes":["finding","audit_pack","management_review"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:9.3","framework":"ISO 9001","clause":"9.3","title":"Management review","summary":"Top management reviews the QMS at planned intervals against defined inputs (status of actions, changes, performance, audit results, nonconformities, customer feedback, risks) and records decisions on improvement, change and resource needs.","recordTypes":["management_review"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:10.2","framework":"ISO 9001","clause":"10.2","title":"Nonconformity and corrective action","summary":"On a nonconformity, react and correct it, evaluate the need to eliminate the cause through root-cause analysis, implement corrective action, review effectiveness, and retain records of the nonconformity and actions taken. Verifier independence supports objectivity.","recordTypes":["finding"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
  {"id":"ISO9001:10.3","framework":"ISO 9001","clause":"10.3","title":"Continual improvement","summary":"Continually improve the suitability, adequacy and effectiveness of the QMS, using analysis results, management review outputs, and corrective actions to identify improvement opportunities.","recordTypes":["management_review","finding"],"version":"2015","kind":"standard","jurisdiction":"ISO","categoryNative":"QMS — applies org-wide, not per-operation","riskTier":"management_system"},
];
