-- DronOps requirement_defs seed ADDENDUM v1.1 (2026-06-07) — Sultanate of Oman
-- Sources: CAR-102 Remote Piloted Aircraft v0.20 (JNC revised amendment) ·
-- CAR-47 Aircraft Registration Marks Rev 05 · AWR 033 Drone Permit Application
-- Rev 8 · CAA circular resuming permits (green zones / Serb platform,
-- effective 25 May 2026).
-- CAUTION: CAR-102 on file is a draft amendment revision (v0.20); confirm the
-- current promulgated issue with Oman CAA before regulator-facing assertions.
-- Jurisdiction derivation for converter: framework 'CAR-102', 'CAR-47',
-- 'CAA AWR 033' → 'Oman'. kind: all 'regulation' except AWR033 rows = 'guidance'
-- (application form requirements / acceptable means).

insert into requirement_defs (id, framework, clause, title, summary, record_types, version) values

('CAR102:015','CAR-102','CAR 102.015','No falsification, reproduction or alteration',
 'Fraudulent or intentionally false statements, and reproduction or alteration of certificates, records or reports required under CAR-102, are prohibited and ground certificate action.',
 array['document','flight_record'],'v0.20'),
('CAR102:020','CAR-102','CAR 102.020','Operation only in approved areas (green zones)',
 'RPA may be operated only in areas approved by the Authority; per the May 2026 resumption circular, operations are permitted within designated green zones identified on the Serb platform.',
 array['mission_record'],'v0.20'),
('CAR102:025-12','CAR-102','CAR 102.025(12)','36-month retention of liability-relevant records',
 'Operators must retain for at least 36 months any records that could serve to establish responsibilities and liability between operators, remote pilots and other parties; stored protected from damage, alteration and theft.',
 array['flight_record','maintenance_record','audit_pack'],'v0.20'),
('CAR102:065','CAR-102','CAR 102.065 / 102.305\u2013315','RPA Operator Certificate (ROC) for certain operations',
 'Certain RPA operations require certification as an RPA Operator; application, eligibility and conditions per Subpart F, including documented practices and procedures.',
 array['document','declaration'],'v0.20'),
('CAR102:075','CAR-102','CAR 102.075','No operation over populous areas',
 'RPA must not be operated over populous areas except as approved; mission planning must demonstrate compliance.',
 array['mission_record','risk_assessment'],'v0.20'),
('CAR102:115','CAR-102','CAR 102.115','Operational records control and 24-month retention',
 'The operator must establish and implement procedures to control UA operation records; records stored protected from damage, alteration and theft and retained at least 24 months.',
 array['flight_record','document','audit_pack'],'v0.20'),
('CAR102:125','CAR-102','CAR 102.125','Autonomous operations conditions',
 'Autonomous RPA operations are subject to the conditions of this clause and associated approvals.',
 array['mission_record'],'v0.20'),
('CAR102:150','CAR-102','CAR 102.150 / 102.240','Controlled airspace and sense-and-avoid approval',
 'Operations in controlled airspace require special approval including sense-and-avoid capability requirements; prohibited/restricted area rules apply.',
 array['mission_record'],'v0.20'),
('CAR102:180','CAR-102','CAR 102.180','Maintenance, inspections and condition for safe operation',
 'RPA must be maintained and inspected and be in a condition for safe operation before flight.',
 array['maintenance_record','mission_record'],'v0.20'),
('CAR102:185','CAR-102','CAR 102.185 / 102.190','Remote pilot medical condition and incapacitation',
 'Remote pilots must meet medical condition requirements; physical or mental incapacitation prohibits operation.',
 array['credential'],'v0.20'),
('CAR102:195','CAR-102','Subpart D/E (102.195\u2013270)','Remote pilot certification and licensing',
 'Remote pilots require certification (Subpart D) and, where applicable, a Remote Pilot Licence (Subpart E) with eligibility, conditions, duration and cancellation provisions.',
 array['credential','training_record'],'v0.20'),
('CAR102:320','CAR-102','CAR 102.320','Chief Remote Pilot functions and duties',
 'Certified RPA operators must designate a Chief Remote Pilot with defined functions and duties over operational standards and crew.',
 array['personnel_record','document'],'v0.20'),
('CAR102:335','CAR-102','CAR 102.335','Personnel compliance with operator procedures',
 'Persons must comply with the certified RPA operator\u2019s documented practices and procedures.',
 array['document','training_record'],'v0.20'),
('CAR102:G-IMM','CAR-102','Subpart G','Immediate reporting of accidents and serious incidents',
 'Accidents or serious incidents involving moderate/fatal injury, drone crash, or jeopardy to other aircraft or the public must be reported immediately to the 24-hour CAA Flight Safety Department (telephone/email channels published in Subpart G).',
 array['occurrence'],'v0.20'),
('CAR102:G-3D','CAR-102','Subpart G','Listed incident types reported within 3 days',
 'Listed incident types involving drone operations must be reported via the CAA incident reporting system (caa.gov.om) within three days of occurrence.',
 array['occurrence'],'v0.20'),
('CAR47:MARKS','CAR-47','CAR 47 (Rev 05)','Registration marks for unmanned aircraft',
 'Aircraft operated with no pilot on board are classified as unmanned and are subject to registration mark assignment and display requirements under CAR-47.',
 array['registration'],'Rev 05'),
('AWR033:PERMIT','CAA AWR 033','AWR 033 Rev 8','Drone permit application per operation (new / extension / renewal)',
 'Operations require a CAA permit; the application captures operation type, company category, purpose, full aircraft particulars (type, model, serial, weights, frequency, ceiling, range, speed, endurance, navigation systems, camera, control method, VLOS/BVLOS), investor/owner/operator particulars, declarations, per-location coordinates (governorate/wilayat/village, lat/long), required operational altitude (max 400 ft / 122 m AGL-MSL), and proposed flying dates and times; permit number issued on approval.',
 array['mission_record','registration'],'Rev 8'),
('AWR033:MEDIA','CAA AWR 033','AWR 033 Rev 8 (Attention note)','Media announcements must credit CAA authorization',
 'Any announcement of drone operations in media (TV, radio, press, social media) must state that the operation is authorized by the Civil Aviation Authority.',
 array['mission_record'],'Rev 8');
