-- DronOps requirement_defs seed v1.0 (2026-06-07)
-- Sources: CAR-UAC Issue 02 (GCAA, UAE federal) · DCAR-UAS Issue 03
-- DCAA/DCAR/2025/00007 (Dubai, incl. DUOSAM OM appendix) · GACAR Part 107 v5.0
-- (KSA) · GACAR Part 48 (KSA) · GACA AC 107-01 (KSA acceptable-means guidance)
-- Summaries are paraphrased operational interpretations for compliance tracking;
-- the source regulation text remains authoritative.
-- record_types vocabulary: flight_record, maintenance_record, document,
-- credential, training_record, occurrence, finding, management_review,
-- mission_record, risk_assessment, registration, insurance, duty_record,
-- personnel_record, declaration, audit_pack

insert into requirement_defs (id, framework, clause, title, summary, record_types, version) values

-- ============ GCAA UAE FEDERAL — CAR-UAC Issue 02 ============
('CARUAC:015a','CAR-UAC','UAC.015(a)','Accountable person appointed',
 'Operator must appoint an accountable person with corporate authority and funding access responsible for regulatory compliance.',
 array['document','personnel_record'],'Issue 02'),
('CARUAC:015b','CAR-UAC','UAC.015(b)','Registration and insurance before operation',
 'Every UA must be registered and appropriately insured before any operation commences.',
 array['registration','insurance'],'Issue 02'),
('CARUAC:015c','CAR-UAC','UAC.015(c)','Change notification to authority',
 'Operator must notify GCAA/LAA in sufficient time before changes to accountable person, operator details, UA types, fleet size, or type of operations.',
 array['document'],'Issue 02'),
('CARUAC:015d','CAR-UAC','UAC.015(d)','Equipment serviceability and maintenance',
 'All UA instruments and equipment required for safe operation must be available, serviceable, and maintained per manufacturer and operator maintenance instructions.',
 array['maintenance_record'],'Issue 02'),
('CARUAC:015e','CAR-UAC','UAC.015(e)','Pilot competence assurance',
 'Operator must ensure each UA pilot is competent for the intended operation with required skills and regulatory knowledge.',
 array['credential','training_record'],'Issue 02'),
('CARUAC:015f','CAR-UAC','UAC.015(f)','Controlled storage and release of UA',
 'UA must be stored securely and released for pilot use in a controlled, documented manner.',
 array['document','mission_record'],'Issue 02'),
('CARUAC:015h','CAR-UAC','UAC.015(h)','Operational records control and 24-month retention',
 'Operator must establish procedures to control UA operation records; records protected from damage, alteration and theft, retained at least 24 months.',
 array['flight_record','document','audit_pack'],'Issue 02'),
('CARUAC:015h-AMC','CAR-UAC','AMC to UAC.015(h)','Flight mission log minimum contents',
 'Flight logs must include date, route/GPS coordinates, start/end times, pilot name, observations/incidents/equipment failures, airspace approval reference, UA details (model, serial, registration, weight, colour), and pilot training certificate/licence references.',
 array['flight_record'],'Issue 02'),
('CARUAC:020','CAR-UAC','UAC.020','UA pilot licensing',
 'Pilots must hold the applicable GCAA UA pilot licence for the operation conducted.',
 array['credential'],'Issue 02'),
('CARUAC:025','CAR-UAC','UAC.025','Airspace approval per operation',
 'UA operations require applicable airspace approval; approvals must be obtained and referenced before flight.',
 array['mission_record'],'Issue 02'),
('CARUAC:035a','CAR-UAC','UAC.035(a-c)','Accident and serious incident reporting within 3 hours',
 'Accidents and serious incidents must be reported to GCAA (and local police for accidents) within 3 hours with all pertinent information; follow-up report on preventive actions where relevant.',
 array['occurrence','finding'],'Issue 02'),
('CARUAC:035d','CAR-UAC','UAC.035(d)','Occurrence reporting via ROSI',
 'Operator must report occurrences (crashes, signal interference, near miss, collisions, public nuisance, operations outside assigned area, injuries, lost UA) to GCAA through the ROSI system.',
 array['occurrence'],'Issue 02'),
('CARUAC:040','CAR-UAC','UAC.040','UOA continued validity (annual)',
 'UA Operator Authorisation is valid for one year subject to continued compliance, valid security clearance, and authority access to facilities, equipment, documents and records at any time.',
 array['document','audit_pack'],'Issue 02'),
('CARUAC:045','CAR-UAC','UAC.045','Oversight findings and CAPA timelines',
 'Authority surveillance findings are classified Level 1/2/3 requiring corrective action plans within 7/60/90 calendar days respectively; repeated Level 2 findings escalate to Level 1.',
 array['finding'],'Issue 02'),

-- ============ DCAA DUBAI — DCAR-UAS Issue 03 ============
('DCAR:ORG-AUTH','DCAR-UAS','UAS.ORG','Operator authorization and DCAR compliance declaration',
 'Operator organizations must be authorized and registered with DCAA, declare compliance with DCAR-UAS, and hold a Dubai UAS Operator Authorization; advanced category requires DUOSAM safety approval.',
 array['document','declaration'],'Issue 03'),
('DCAR:ORG-REG','DCAR-UAS','UAS.ORG','Registration of all personnel and assets',
 'Operator must register all personnel and assets involved in operations (pilots, operation crew, maintenance crew, safety personnel, UA, ground controllers, payloads, safety add-ons) and keep registrations updated on change.',
 array['personnel_record','registration'],'Issue 03'),
('DCAR:UOR-RECORDS','DCAR-UAS','UAS.UOR','Operational records control and 24-month retention',
 'Operator must establish and implement procedures controlling UA operation records; records stored protected from damage, alteration and theft, retained at least 24 months, and provided to DCAA on request.',
 array['flight_record','document','audit_pack'],'Issue 03'),
('DCAR:UOR-AMEND','DCAR-UAS','UAS.UOR','Notification of process and manual amendments',
 'Operator must notify DCAA of amendments to processes, procedures and manuals including pre-flight, flight, post-flight, training, safety and emergency management.',
 array['document'],'Issue 03'),
('DCAR:UOR-CREW','DCAR-UAS','UAS.UOR','Crew qualification and competence',
 'Operator must ensure operational crews are qualified and competent for the intended operations.',
 array['credential','training_record'],'Issue 03'),
('DCAR:UOR-FLTLOG','DCAR-UAS','UAS.UOR','Flight log maintained and pilot-signed',
 'During operations flight logs must be properly maintained, all observations and incidents recorded, and the flight log signed by the UA pilot at the end of the operation.',
 array['flight_record'],'Issue 03'),
('DCAR:OM-RETENTION','DCAR-UAS','DUOSAM OM — Retention',
 'Three-year retention for advanced-category documentation',
 'All important operation documents kept (digital or analogue) at least 3 years after end of operation; personnel records 3 years after the person leaves or changes position; protected against loss/alteration; available for authority inspection. Covers authorizations, flight records, maintenance records, qualification/training records, and safety meeting minutes.',
 array['flight_record','maintenance_record','training_record','management_review','audit_pack'],'Issue 03'),
('DCAR:OM-DOCCTRL','DCAR-UAS','DUOSAM OM — Document control','Controlled distribution and current-version discipline',
 'Employees must receive current document sets and revision updates; current revision lists maintained and accessible; authorized-personnel lists kept for maintenance, pre/post-flight inspections, and qualified remote pilots.',
 array['document','personnel_record'],'Issue 03'),
('DCAR:OM-DUTY','DCAR-UAS','DUOSAM OM — Duty (OSO#17)','Duty hours and rest period limits',
 'Flight duty hour maxima and rest period minima apply to all crew involved in UAS operations; company agreements may tighten but never extend the limits.',
 array['duty_record'],'Issue 03'),
('DCAR:OM-OCC72','DCAR-UAS','DUOSAM OM — Occurrence reporting','72-hour occurrence reporting to DCAA',
 'Occurrences endangering aircraft, persons, equipment or installations, and related safety information, must be reported to DCAA within 72 hours of awareness; accidents, serious incidents and property damage additionally reported.',
 array['occurrence'],'Issue 03'),
('DCAR:OM-ERP','DCAR-UAS','DUOSAM OM — Part E','Emergency response plan and training records',
 'An ERP must exist with preparation/briefing procedures and post-emergency reporting obligations; ERP training conducted and recorded per crew member.',
 array['document','training_record'],'Issue 03'),
('DCAR:OM-MAINT','DCAR-UAS','DUOSAM OM — Part M','Maintenance program, software updates and evidence',
 'Maintenance procedures including software/firmware update control must be documented, with evidence records (e.g. technical logbook, flight tests of contingency and emergency procedures).',
 array['maintenance_record'],'Issue 03'),

-- ============ GACA KSA — GACAR Part 107 v5.0 ============
('GACAR107:107.5','GACAR Part 107','§ 107.5','No falsification of records',
 'No fraudulent or intentionally false statements in any application, record, report or document required under this Part; falsification grounds for certificate action.',
 array['document','flight_record'],'v5.0'),
('GACAR107:107.7','GACAR Part 107','§ 107.7','Inspection and demonstration of compliance',
 'Certificate holders must, on GACA request, make available certificates, documents and records and allow inspection/testing to determine compliance.',
 array['audit_pack'],'v5.0'),
('GACAR107:107.9','GACAR Part 107','§ 107.9','Occurrence reporting within 10 days; NTSC for serious',
 'RPIC must report to GACA within 10 calendar days operations involving serious injury or loss of consciousness, property damage (other than the UA), missing/inaccessible UA, fly-away, or manned-aircraft interference; serious incidents/accidents also to NTSC.',
 array['occurrence'],'v5.0'),
('GACAR107:107.19','GACAR Part 107','§ 107.19','Condition for safe operation',
 'No operation unless the UAS is in a condition for safe operation; pre-flight checks must confirm this and operation must cease when no longer safe.',
 array['mission_record','maintenance_record'],'v5.0'),
('GACAR107:107.57','GACAR Part 107','§ 107.57','Preflight assessment, briefing, checks and 3-year flight logbook',
 'Before flight the RPIC must assess the operating environment (weather, airspace and restrictions, persons/property, ground hazards), brief all participants on conditions, emergency/contingency procedures, roles and hazards, verify control links and power. All flights recorded in a logbook with date, time, PIC and crew, aircraft registration, take-off/landing areas, total flight time, type of operation, flight rules, and deviations; records kept 3 years and ready for inspection.',
 array['flight_record','mission_record'],'v5.0'),
('GACAR107:107.59','GACAR Part 107','§ 107.59','Operating limitations for small UA',
 'Operations must remain within the prescribed limitations (altitude, speed, visibility and related constraints) applicable to the category and authorization.',
 array['flight_record','mission_record'],'v5.0'),
('GACAR107:107.71','GACAR Part 107','§ 107.71','Aeronautical knowledge recency (24 months)',
 'No person may operate a small UAS unless they passed an initial or recurrent knowledge test or recognized training within the previous 24 calendar months.',
 array['credential','training_record'],'v5.0'),
('GACAR107:107.117','GACAR Part 107','§ 107.117','Operations Manager duties and reference library',
 'The Operations Manager must ensure operations comply with the Part, maintain qualification records of every person operating UAS, monitor operational standards and proficiency, and maintain a complete current reference library: operations manual, operational flight plans, remote pilot certificates, operational authorizations, operations risk assessments, declarations of compliance, UOC, and SMS documents.',
 array['document','credential','risk_assessment','declaration'],'v5.0'),
('GACAR107:107.123','GACAR Part 107','§ 107.123','OA/UOC application content (manuals, RA, procedures)',
 'Applications must address responsible persons, locations, an operational risk assessment with mitigations, occurrence reporting procedures, personnel licensing/training/medical requirements, aircraft and control station details, maintenance procedures, in-flight procedures including minimum distances, and cargo/dangerous-goods procedures where intended.',
 array['document','risk_assessment'],'v5.0'),
('GACAR107:107.133','GACAR Part 107','§ 107.133','Operate within OA/UOC conditions',
 'Operations must comply with the conditions and limitations stated in the Operational Authorization or UAS Operator Certificate.',
 array['mission_record'],'v5.0'),
('GACAR107:107.135','GACAR Part 107','§ 107.135','Notification of changes to application basis',
 'Changes to the matters addressed in the OA/UOC application must be managed and notified per GACA requirements before implementation.',
 array['document'],'v5.0'),
('GACAR107:107.139','GACAR Part 107','§ 107.139','UOC records: crew per flight and maintenance, 3-year retention',
 'UOC holders must maintain records naming remote pilots and crew for each flight with flight times, and records of maintenance, modification or repair (who performed, dates, parts/equipment for modifications, completion instructions); records transferred with ownership, available to GACA on request, retained 3 years after creation.',
 array['flight_record','maintenance_record','personnel_record'],'v5.0'),
('GACAR107:107.145','GACAR Part 107','§ 107.145','Personnel compliance with documented procedures',
 'Persons employed by or assisting an operator must comply with the operator''s documented practices and procedures.',
 array['document','training_record'],'v5.0'),
('GACAR107:107.149','GACAR Part 107','§ 107.149','Safety Management System',
 'UOC operators must have an SMS including safety policy, hazard identification and risk management for aviation and third-party risks, internal reporting and analysis of hazards/incidents/accidents with recurrence prevention, measurable safety goals, internal audits and regular management reviews, and competency training — documented and scaled to the organization.',
 array['occurrence','finding','management_review','risk_assessment','training_record'],'v5.0'),
('GACAR107:107.171','GACAR Part 107','§ 107.171','Insurance for Specific operations',
 'Adequate third-party and cargo liability insurance must exist for every flight regardless of ownership/lease, covering damage, injury, war, terrorism, hijacking, sabotage, unlawful seizure and civil commotion; dangerous-goods carriage explicitly listed where applicable.',
 array['insurance'],'v5.0'),
('GACAR107:107.203','GACAR Part 107','§ 107.203 (Subpart E)','Declaration of Compliance where required',
 'UAS used for operations requiring a declared performance standard must be covered by a Declaration of Compliance to GACA (manufacturer or operator declaration).',
 array['declaration'],'v5.0'),
('GACAR107:107.211','GACAR Part 107','§ 107.211','Declared-UAS documentation to owners',
 'Declarants must make available to owners a maintenance program (servicing instructions and inspection program), mandatory actions, and a UAS operating manual covering system description, weight/CG limits, altitude/velocity envelopes, environmental effects, crew-injury characteristics, third-party protection features, and degradation warnings.',
 array['document','maintenance_record'],'v5.0'),
('GACAR107:107.213','GACAR Part 107','§ 107.213','Declaration record retention',
 'Records supporting a Declaration of Compliance must be retained per Subpart E and made available to GACA.',
 array['declaration','audit_pack'],'v5.0'),

-- ============ GACA KSA — GACAR Part 48 ============
('GACAR48:48.3','GACAR Part 48','§ 48.3','Registration requirement (MTOM ≥ 250 g)',
 'Unmanned aircraft of 250 g MTOM or more (and others meeting listed conditions) must be registered and marked before operation.',
 array['registration'],'current'),
('GACAR48:48.11','GACAR Part 48','§ 48.11','Maintain current registration information',
 'Certificate holders must keep registration information current and update the registry when details change.',
 array['registration'],'current'),
('GACAR48:48.13','GACAR Part 48','§ 48.13/48.15','Registration validity and 3-year renewal',
 'Certificates of Aircraft Registration expire no later than 3 years after issue; renewal by verifying or updating registry information within the six months preceding expiry; effectiveness ends on revocation, cancellation, expiry, transfer or other listed events.',
 array['registration'],'current'),
('GACAR48:48.19','GACAR Part 48','§ 48.19/48.21','Unique identifier display',
 'No operation unless the registered aircraft displays its unique identifier per the display and location requirements.',
 array['registration'],'current'),
('GACAR48:48.23','GACAR Part 48','§ 48.23','Specific-category eligibility label',
 'Aircraft used in Specific category operations must display a label or QR code indicating eligibility for Specific category operations.',
 array['registration'],'current'),

-- ============ GACA KSA — AC 107-01 (acceptable means / guidance) ============
('AC107-01:PILOT-LOG','GACA AC 107-01','Flight time recording','Pilot logbook minimum contents',
 'Pilots and related personnel should maintain a logbook (paper or electronic, producible to GACA) recording name, UA type and serial, flight time, purpose and outcome of flight, and operational/training details — supporting certificate renewal and scope changes.',
 array['flight_record','personnel_record'],'AC 107-01'),
('AC107-01:MAINT-LOG','GACA AC 107-01','§ 107.123(b) maintenance','Aircraft maintenance logbook contents',
 'Maintenance logbooks should record UA model/serial, engine and propeller identification, GCS details, defects and rectifications with component changes, time in service of aircraft and components, finite-life/overhaul item times, airworthiness directive and service-information tracking, purpose of flight and area, pilot identification, and legible records of all inspections (date, inspector) and modifications.',
 array['maintenance_record'],'AC 107-01'),
('AC107-01:CREW-AUTH','GACA AC 107-01','Observers and support crew','Written crew authorization and ongoing training records',
 'Observers and support crew should be trained and authorized in writing by the operator, with records of ongoing training and site authorizations held by operator and crew member.',
 array['training_record','personnel_record'],'AC 107-01'),
('AC107-01:DOC-AMEND','GACA AC 107-01','§ 107.123(b)(15)','Controlled amendment of certificated documentation',
 'Operators need an amendment process for application documentation: list of effective pages, chronological amendment record, and an amendment control sheet tracking the process.',
 array['document'],'AC 107-01'),
('AC107-01:INFOSEC','GACA AC 107-01','Security measures','Protection of information and record-keeping systems',
 'Operators should implement measures against unauthorized access to information and record-keeping systems.',
 array['document','audit_pack'],'AC 107-01');
